apiVersion: v1
data:
  REPOS: redhat-developer/yaml-language-server, redhat-developer/vscode-yaml, redhat-developer/vscode-java, redhat-developer/odo, eclipse/eclipse.jdt.ls,
    eclipse/jkube, code-ready/crc, redhat-developer/vscode-xml, eclipse/lemminx, kcp-dev/kcp, shipwright-io/build
  GF_SECURITY_ADMIN_PASSWORD: foobar
  GF_USERS_ALLOW_SIGN_UP: "false"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: metrics
  name: metrics-env