{
 "title": "GitHub Stats",
 "description": "A docker stack which uses Grafana to collect GitHub statistics for selected Repositories",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "repo", "query": { "query": "label_values(repo)" } }
  ]
 },
 "panels": [
  {
   "title": "Repository Stars",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_stars{repo=\"$repo\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Open Issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_open_issues{repo=\"$repo\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_forks{repo=\"$repo\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Pull Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_pull_request_count{repo=\"$repo\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_watchers{repo=\"$repo\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Repo Size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_repo_size_kb{repo='$repo'}"
    }
   ]
  }
 ]
}